CONFIG_PM_DEVICE=y
CONFIG_ZMK_SLEEP=y
# 1800000 ms = 30 minutes (default is 15 min)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_ZMK_BATTERY_REPORTING=y

# Disable 2M PHY for better interference resistance near 2.4 GHz devices
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
