manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: perrwa
      url-base: https://github.com/perrwa
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-component-raytac-dongle
      remote: perrwa
      revision: 239191ade065bd62404d0f32cc36ca58e3d275d7
  self:
    path: config
