manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    # - name: rschenk
    #   url-base: https://github.com/rschenk
    - name: venator
      url-base: https://github.com/venator
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    # - name: zmk-component-raytac-dongle
    #   remote: rschenk
    #   revision: main
    - name: zmk-component-raytac-dongle
      remote: venator
      revision: main
  self:
    path: config
