name: Build ZMK DFU Firmware
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: raytac_mdbt50q_cx_40
            shield: corne_dongle
            artifact-name: corne_dongle

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel \
            ninja-build gperf ccache dfu-util device-tree-compiler git cmake gcc-arm-none-eabi

      - name: Install West and NRF tools
        run: |
          pip3 install --upgrade pip
          pip3 install west nrfutil pyelftools twisted pyserial
          cd config
          west init -l .
          west update
          west zephyr-export
          west sdk install

      - name: Export Zephyr environment
        run: |
          cd config
          source zephyr/zephyr-env.sh
          cd ..

      - name: Build ZMK firmware and HEX
        run: |
          source config/zephyr/zephyr-env.sh
          west build -b ${{ matrix.board }} -s zmk/app -d build/${{ matrix.artifact-name }} -- -DZMK_CONFIG=config
          west build -d build/${{ matrix.artifact-name }} -t zephyr.hex

      - name: Package DFU zip
        run: |
          mkdir -p release
          nrfutil pkg generate \
            --application build/${{ matrix.artifact-name }}/zephyr.hex \
            --hw-version 52 \
            --sd-req 0x00 \
            release/firmware-${{ matrix.artifact-name }}.zip

      - name: Upload DFU Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: release/firmware-${{ matrix.artifact-name }}.zip
