name: Build ZMK firmware DFU and HEX
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - board: nice_nano_v2
          #   shield: corne_left
          #   artifact-name: corne_left
          # - board: nice_nano_v2
          #   shield: corne_right
          #   artifact-name: corne_right
          - board: raytac_mdbt50q_cx_40
            shield: corne_dongle
            artifact-name: corne_dongle
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install nrfutil
        run: pip install nrfutil

      - name: Set up Zephyr/West
        run: |
          # install west/zephyr SDK as needed
          pip install west
          west init -l config
          west update

      - name: Build ZMK firmware
        run: |
          west build -b ${{ matrix.board }} -s zmk/app -d build/${{ matrix.artifact-name }} \
            -- -DZMK_CONFIG=config

      - name: Generate HEX for DFU
        run: |
          west build -d build/${{ matrix.artifact-name }} -t zephyr.hex

      - name: Package DFU zip
        run: |
          nrfutil pkg generate \
            --application build/${{ matrix.artifact-name }}/zephyr.hex \
            --hw-version 52 \
            --sd-req 0x00 \
            release/firmware-${{ matrix.artifact-name }}.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            release/firmware-${{ matrix.artifact-name }}.zip
