name: Build ZMK DFU Firmware
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: raytac_mdbt50q_cx_40
            shield: corne_dongle
            artifact-name: corne_dongle

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel \
            ninja-build gperf ccache dfu-util device-tree-compiler wget git cmake gcc-arm-none-eabi

      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install west nrfutil

      - name: Initialize west workspace
        run: |
          west init -l config
          west update

      - name: Set up Zephyr SDK (official method)
        run: |
          pip3 install -r config/zephyr/scripts/requirements.txt
          # Export Zephyr environment variables
          export ZEPHYR_BASE=$(pwd)/config/zephyr
          west zephyr-export
        shell: bash

      - name: Build ZMK firmware and HEX
        run: |
          west build -b ${{ matrix.board }} -s zmk/app -d build/${{ matrix.artifact-name }} -- -DZMK_CONFIG=config
          west build -b ${{ matrix.board }} -s zmk/app -d build/${{ matrix.artifact-name }} -t zephyr.hex -- -DZMK_CONFIG=config

      - name: Package DFU zip
        run: |
          mkdir -p release
          nrfutil pkg generate \
            --application build/${{ matrix.artifact-name }}/zephyr.hex \
            --hw-version 52 \
            --sd-req 0x00 \
            release/firmware-${{ matrix.artifact-name }}.zip

      - name: Upload DFU Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: release/firmware-${{ matrix.artifact-name }}.zip
